name: my first workflow

on:
  workflow_dispatch: 

jobs:
  terraform_init:
    name: Terraform init task 
    runs-on: self-hosted
    permissions: 
      contents: read
    steps:
      - name: my first terraform init 
        run: echo hello world

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.SECRETS}}

      - name: init
        run: terraform init  
        working-directory: ENVIORNMENT/DEV
    
    
